In [ ]:
from google.colab import files
uploaded = files.upload()

Saving reed_data_analyst_latest (1).csv to reed_data_analyst_latest (1).csv


In [ ]:
for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'. format(name= fn, length=len(uploaded[fn])))

User uploaded file "reed_data_analyst_latest (1).csv" with length 1649799 bytes


In [ ]:
import pandas as pd
import io

In [ ]:
df= pd.read_csv(io.BytesIO(uploaded['reed_data_analyst_latest (1).csv']))
df.head()

web-scraper-order  ...                                         pages-href
0   1628454831-1436  ...                                                NaN
1   1628455695-1752  ...  https://www.reed.co.uk/jobs/data-analyst-jobs-...
2   1628455409-1639  ...                                                NaN
3   1628455063-1527  ...                                                NaN
4   1628454193-1193  ...                                                NaN

[5 rows x 11 columns]

In [ ]:
len(df)

634

In [ ]:
print(df.shape)

(634, 11)


In [ ]:
df['job_description'][0]

'A leading online retail & groceries brand is undergoing considerable investment in their Insight & Analytics teams across the business. \n\nThis is a fantastic opportunity to join a data-driven e-commerce business at the forefront of technological innovation. Working in an entrepreneurial start-up environment with the backing of a huge brand.\n\nThe Role:\n\n*The main purpose of the role is to Drive Data quality improvement across the business.\n*Support the data governance programme (and associated data governance council) through detailed data analysis.\n*Builds tools and dashboards to monitor quality and provide alerts to all data users.\n*Manage, monitor, assess, resolve data quality issues with EDW, Data Marts and reporting solutions.\n*Answer business questions about data, be the bridge between data and Insight.\n*Assess and profile new data sources to provide input to integration design.\n*Collaborate with business users and analysts to capture business rules and data quality r

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer(max_df=0.75,min_df=2,stop_words='english')
dtm=cv.fit_transform(df['job_description'])
dtm

<634x4821 sparse matrix of type '<class 'numpy.int64'>'
	with 81688 stored elements in Compressed Sparse Row format>

In [ ]:
from sklearn.decomposition import LatentDirichletAllocation
LDA=LatentDirichletAllocation(n_components=10,random_state=42)
LDA.fit(dtm)


LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=10, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

### 3 steps away
grab the vocab
grab the topic
and finally grab the highest prob. word per topic

In [ ]:
len(cv.get_feature_names())

4821

In [ ]:
type(cv.get_feature_names())

list

In [ ]:
cv.get_feature_names()[2550]

'levelproficiency'

In [ ]:
import random
for i in range(10):
  random_word_id=random.randint(0,4821)
  print(cv.get_feature_names()[random_word_id])


discrepancyresolve
mind
promote
syndicate
starts
guidelines
utility
sought
ordinator
eye


In [ ]:
len(LDA.components_)

10

In [ ]:
LDA.components_.shape

(10, 4821)

In [ ]:
LDA.components_

array([[ 0.1       , 46.14270726,  0.1       , ...,  0.1       ,
         0.1       ,  0.1       ],
       [ 0.52514133, 78.766567  ,  0.1       , ...,  0.10001425,
         0.10001247,  0.1       ],
       [ 2.10000318,  0.36740769,  0.1       , ...,  0.1       ,
         0.1       ,  0.1       ],
       ...,
       [ 1.3910057 , 25.34785856,  0.1       , ...,  0.10004562,
         1.10000062,  2.1       ],
       [ 0.10000823,  0.10000738,  0.1       , ...,  0.10000162,
         0.1       ,  0.1       ],
       [ 0.10000551, 87.47736796,  3.1       , ...,  0.10000053,
         1.06533279,  0.1       ]])

In [ ]:
LDA.components_[0]

array([ 0.1       , 46.14270726,  0.1       , ...,  0.1       ,
        0.1       ,  0.1       ])

In [ ]:
len(LDA.components_[1])

4821

In [ ]:
single_topic = LDA.components_[0]

In [ ]:
single_topic.argsort()

array([4467, 2842, 2917, ..., 3680, 3490, 3658])

In [ ]:
#word least representative of this topic
single_topic[2550]

0.10000000002008995

In [ ]:
#word least representative of this topic
single_topic[2095]

0.10001779273590945

In [ ]:
#word most representative of this topic
single_topic[2550]

0.10000000002008995

In [ ]:
#top 10 words for this topic
single_topic.argsort()[-10:]

array([4061, 1997,  129, 4359, 2327, 2681,  337, 3680, 3490, 3658])

In [ ]:
top_word_indeces=single_topic.argsort()[-10:]


In [ ]:
tures a

In [ ]:
for index in top_word_indeces:
  print(cv.get_feature_names()[index])

solutions
global
ability
team
insurance
management
analysis
requirements
quality
reporting


lets confirm by using .transform() on our vectorized articles to attach a label number. But firts, let's view all the 10 topics found

In [ ]:
#array_val=[]
for index,topic in enumerate(LDA.components_):
  print(f'THE TOP 10 WORDS FOR TOPIC #{index}')
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  #for i in topic.argsort()[-15:]:
   #print(cv.get_feature_names()[i])
   #values= cv.get_feature_names()[i]
   #print(values)
   #array_val.append(values)
   #array_words_combine.append(cv.get_feature_names()[i])
  

THE TOP 10 WORDS FOR TOPIC #0
['reports', 'join', 'sql', 'company', 'governance', 'solutions', 'global', 'ability', 'team', 'insurance', 'management', 'analysis', 'requirements', 'quality', 'reporting']
THE TOP 10 WORDS FOR TOPIC #1
['remote', 'insights', 'll', 'market', 'making', 'opportunity', 'looking', 'new', 'power', 'sql', 'team', 'bi', 'product', 'work', '000']
THE TOP 10 WORDS FOR TOPIC #2
['sql', 'ability', 'people', 'requirements', 'ensure', 'mi', 'using', 'management', 'master', 'team', 'group', 'support', 'analysis', 'work', 'able']
THE TOP 10 WORDS FOR TOPIC #3
['employment', 'excel', 'analysis', 'customer', 'recruitment', 'client', 'company', 'looking', 'management', 'support', 'job', 'team', 'work', 'reporting', 'new']
THE TOP 10 WORDS FOR TOPIC #4
['new', 'processes', 'reports', 'requirements', 'company', 'knowledge', 'client', 'ability', 'excel', 'strong', 'senior', 'work', 'sql', 'analysis', 'team']
THE TOP 10 WORDS FOR TOPIC #5
['warehouse', 'financial', 'quality', '

In [ ]:
array_val=[]
for index,topic in enumerate(LDA.components_):
  print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
  #print([cv.get_feature_names()[i] for i in topic.argsort()[-10:]])
  for i in topic.argsort()[-25:]:
   #print(cv.get_feature_names()[i])
   values= cv.get_feature_names()[i]
   #print(values)
   array_val.append(values)
   #array_words_combine.append(cv.get_feature_names()[i])
  print("\n")

THE TOP 15 WORDS FOR TOPIC #0


THE TOP 15 WORDS FOR TOPIC #1


THE TOP 15 WORDS FOR TOPIC #2


THE TOP 15 WORDS FOR TOPIC #3


THE TOP 15 WORDS FOR TOPIC #4


THE TOP 15 WORDS FOR TOPIC #5




In [ ]:
print(array_val)

['service', 'provide', 'project', 'level', 'company', 'technical', 'information', 'analysis', 'clients', 'including', 'client', 'development', 'services', 'solutions', 'working', 'role', 'ability', 'analyst', 'management', 'support', 'experience', 'business', 'work', 'team', 'skills', 'insight', 'new', 'company', 'strong', 'bi', 'looking', 'key', 'knowledge', 'customer', 'digital', 'opportunity', 'excel', 'team', 'client', 'marketing', 'analysis', 'work', 'working', 'analytics', 'sql', 'role', 'business', 'skills', 'experience', 'analyst', 'migration', 'leading', 'key', 'working', 'insights', 'day', 'knowledge', 'skills', 'opportunity', 'sales', 'new', 'business', '000', 'analysis', 'analytical', 'team', 'excel', 'systems', 'sql', 'support', 'management', 'role', 'product', 'analyst', 'experience', 'using', 'employment', 'provide', 'key', 'ensure', 'job', 'systems', 'processes', 'ability', 'reports', 'requirements', 'management', 'information', 'analyst', 'role', 'work', 'new', 'team',

# attaching discovered topic labels to the original articles

In [ ]:
dtm

<634x4821 sparse matrix of type '<class 'numpy.int64'>'
	with 81688 stored elements in Compressed Sparse Row format>

In [ ]:
dtm.shape

(634, 4821)

In [ ]:
len(df)

634

In [ ]:
topic_results=LDA.transform(dtm)

In [ ]:
topic_results.shape

(634, 10)

In [ ]:
topic_results[0]

array([0.59790254, 0.0007695 , 0.00076941, 0.1468137 , 0.00076948,
       0.00076936, 0.00076944, 0.0007694 , 0.24989769, 0.00076949])

In [ ]:
topic_results[0].round(2)

array([0.6 , 0.  , 0.  , 0.15, 0.  , 0.  , 0.  , 0.  , 0.25, 0.  ])

In [ ]:
topic_results[0].argmax()

0

this means that our model thinks that teh first topic belongs to topic 1

combining with original data

In [ ]:
df.head()

web-scraper-order  ...                                         pages-href
0   1628454831-1436  ...                                                NaN
1   1628455695-1752  ...  https://www.reed.co.uk/jobs/data-analyst-jobs-...
2   1628455409-1639  ...                                                NaN
3   1628455063-1527  ...                                                NaN
4   1628454193-1193  ...                                                NaN

[5 rows x 11 columns]

In [ ]:
topic_results.argmax(axis=1)

array([0, 4, 4, 9, 3, 4, 4, 3, 3, 9, 8, 4, 8, 3, 3, 3, 3, 3, 0, 3, 9, 7,
       8, 3, 3, 1, 9, 8, 9, 8, 0, 3, 6, 3, 8, 8, 4, 4, 9, 0, 9, 8, 4, 8,
       4, 9, 7, 4, 4, 3, 1, 3, 4, 3, 4, 3, 3, 7, 3, 8, 7, 1, 8, 8, 1, 3,
       4, 8, 7, 4, 6, 4, 9, 6, 3, 3, 0, 3, 4, 3, 3, 8, 4, 3, 9, 9, 3, 8,
       8, 3, 6, 4, 7, 8, 4, 8, 8, 9, 4, 8, 4, 4, 4, 4, 7, 3, 3, 9, 3, 3,
       7, 4, 4, 7, 7, 4, 7, 7, 3, 0, 9, 3, 9, 5, 8, 3, 3, 9, 0, 9, 4, 8,
       3, 9, 3, 3, 8, 4, 3, 9, 0, 3, 4, 0, 3, 4, 9, 8, 9, 3, 7, 9, 3, 4,
       4, 3, 3, 3, 9, 9, 4, 3, 3, 8, 3, 6, 7, 4, 4, 3, 3, 3, 3, 4, 4, 1,
       8, 3, 3, 4, 8, 4, 3, 5, 8, 0, 3, 5, 8, 4, 4, 3, 4, 3, 7, 8, 9, 3,
       3, 9, 2, 3, 0, 3, 2, 7, 3, 3, 8, 1, 9, 9, 4, 9, 0, 9, 4, 4, 3, 1,
       4, 8, 9, 8, 4, 3, 7, 5, 4, 4, 4, 4, 3, 1, 4, 4, 3, 4, 3, 4, 1, 4,
       3, 5, 3, 4, 3, 3, 4, 7, 7, 3, 4, 7, 5, 0, 0, 4, 3, 4, 0, 9, 4, 9,
       4, 0, 3, 3, 8, 4, 3, 3, 9, 4, 3, 4, 6, 2, 3, 3, 4, 4, 3, 7, 3, 4,
       4, 4, 3, 3, 3, 4, 4, 4, 8, 4, 0, 0, 9, 3, 4,

In [ ]:
len(topic_results.argmax(axis=1))

634

In [ ]:
df['job_description_topic']= topic_results.argmax(axis=1)

In [ ]:
df.head()

web-scraper-order  ... job_description_topic
0   1628454831-1436  ...                     0
1   1628455695-1752  ...                     4
2   1628455409-1639  ...                     4
3   1628455063-1527  ...                     9
4   1628454193-1193  ...                     3

[5 rows x 12 columns]

In [ ]:
df.to_csv('results_LDA3.csv')

#Word2 vec

In [ ]:
import os
import sys
import re
#from gensim.models import Word2Vec
from gensim.models import word2vec

In [ ]:
# Set values for various parameters
feature_size = 100   # Word vector dimensionality  
window_context = 30          # Context window size                                                                                    
min_word_count = 1   # Minimum word count                        
sample = 1e-3   # Downsample setting for frequent words

In [ ]:
w2v_model = word2vec.Word2Vec([array_val], size=feature_size, 
                          window=window_context, min_count=min_word_count,
                          sample=sample)

In [ ]:
w2v_model

In [ ]:
w2v_model.vector_size

100

In [ ]:
w2v_model.wv

In [ ]:
similar_words = {search_term: [item for item in w2v_model.wv.most_similar([search_term])]
                  for search_term in ['data','reporting']}
similar_words

KeyError: ignored